# Generated by Django 4.1.3 on 2023-08-25 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='aboutnew',
        ),
    ]
