# Generated by Django 4.1.3 on 2023-08-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='client/')),
            ],
        ),
    ]
